task_k (MVVM)
MaximBadanov/swiftui_project pull request #11
Opened 2024-04-03 18:25 UTC by MaximBadanov

Task A

Explain the types of architectures
Explain the main difference between MVC and MVVM, VIP
Task B

Implement business logic by MVVM for all screen where you think that's needed

2024-04-10 23:06 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenreViewViewModel/GenreViewViewModel.swift
> +        guard let network = DIContainer.shared.injectDependency(dependency: NetworkService()) else {
You should here take network from DI not inject here

2024-04-10 23:07 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenreViewViewModel/GenreViewViewModel.swift
> +        dataManager = DataManager(network: network)
It should be in DI

2024-04-10 23:13 UTC, iosnickse requested changes

2024-04-10 23:13 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenresScreen.swift
> +                        requestModel: RequestModel(
You must not create Request on view side

2024-04-10 23:13 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenresScreen.swift
> +    @State private var genres: [String] = ["27", "12"]
The genres should be chosen by users not hardcoded

2024-04-10 23:13 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenresScreen.swift
> +                               destination: ResultView(
I think better fetch random movie on result view where should be movie

2024-04-10 23:13 UTC, iosnickse commented on swiftui_project/swiftui_project/NetworkService/NetworkServiceSupport/Urls.swift
> +    case moviesByGenres = "https://api.themoviedb.org/3/discover/movie?&with_genres="
&with_genres should be hardcoded, you should send url/body parameters in network service from request model

2024-04-10 23:13 UTC, iosnickse commented on swiftui_project/swiftui_project/ResultView/MovieView.swift
> +    private let baseURL = "https://image.tmdb.org/t/p/"
Nothing for network or business logic shouldn’t be on view side

2024-04-23 00:12 UTC, iosnickse requested changes

2024-04-23 00:12 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenreViewViewModel/GenreViewViewModel.swift
> +                self.resultViewModel.movie = movie
You shouldn't pass one vm to another VM

2024-04-23 00:12 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenreViewViewModel/GenreViewViewModel.swift
> +                self.resultViewModel.movie = movie
If you want to send data between screen, for simple way (just to show) you must use just let property in view, new input will redraw view and that's it, even without VM

2024-04-26 13:34 UTC, iosnickse commented on swiftui_project/swiftui_project/GenreScreen/GenreButton.swift
> +                    if !GenreButtonViewModel.shared.genres.contains(id) {
All logic must be in vm

2024-04-26 13:35 UTC, iosnickse commented on swiftui_project/swiftui_project/ResultView/MovieView.swift
> +            Text(GenreButtonViewModel.shared.genres[0])
Don’t use indexes by hardcode

2024-04-26 13:36 UTC, iosnickse commented on swiftui_project/swiftui_project/Supports&Extensions/Genre/AllGenres.swift
> +                id: "9648"
Don’t use hardcode here

2024-04-26 13:38 UTC, iosnickse commented on swiftui_project/swiftui_project/Supports&Extensions/Genre/AllGenres.swift
> +                color: .indigo,
Better to fetch genres from api and create model for it or optional init by title or something like that, my opinion that you are good to refactor the enum to model codable and fetch from API

2024-04-26 15:59 UTC, MaximBadanov commented on swiftui_project/swiftui_project/GenreScreen/GenreButton.swift
> +                        print(GenreButtonViewModel.shared.genres)
это для проверки работы логики, пусть пока будет

2024-06-15 07:42 UTC, closed without merging