Getting ALL from API
MaximBadanov/swiftui_project pull request #12
Opened 2024-05-09 16:00 UTC by MaximBadanov

На данном этапе я полностью переделал все на экране с выбором жанра, теперь все жанры мы получаем из из сети
есть небольшая задержка, но тут уже вопрос к будущей теме, которую я просил, многопоточности

2024-05-18 08:06 UTC, iosnickse commented on swiftui_project/swiftui_project/Supports&Extensions/StringExtension/StringExtension.swift
> +        case "history":
For few cases you can use
```swift
case “first”, “second”:
    ….
```

2024-05-18 08:08 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/ViewModel/GenreScreenViewModel.swift
> +    @Published var movie: MovieResponseModel?
private(set)

2024-05-18 08:08 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/ViewModel/GenreScreenViewModel.swift
> +    @Published var genresId: [String] = []
The same

2024-05-18 08:09 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/GenresScreen.swift
> +                               destination: ResultView(title: viewModel.movie?.title ?? "no title", poster: viewModel.movie?.poster ?? "no poster"))
Better on this side send optional value

2024-05-18 08:09 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/GenresScreen.swift
> +                        requestModel: RequestModel(
RequestModel MUST NOT BE on view side

2024-05-18 08:11 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/CarouselOfGenres/ViewModel/GenresViewWithScrollViewModel.swift
> +
Extra

2024-05-18 08:23 UTC, iosnickse commented on swiftui_project/swiftui_project/NetworkService/NetworkService.swift
> +
Why request func only for movies?
You need do generic func for any request, such as movie fetching or weather from another API

2024-05-25 16:38 UTC, MaximBadanov commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/GenresScreen.swift
> +                               destination: ResultView(title: viewModel.movie?.title ?? "no title", poster: viewModel.movie?.poster ?? "no poster"))
I  don't understand, can you explain this a little bit more

2024-05-25 16:39 UTC, MaximBadanov commented on swiftui_project/swiftui_project/NetworkService/NetworkService.swift
> +
I will refactor this after I finish with throwing data between 2 view models(

2024-05-25 16:40 UTC, MaximBadanov commented on swiftui_project/swiftui_project/Supports&Extensions/StringExtension/StringExtension.swift
> +        case "history":
but I have to many cases 🤷🏻‍♂️

2024-05-30 10:03 UTC, iosnickse commented on swiftui_project/swiftui_project/ResultView/MovieView.swift
> +    private let aspectRatioPoster: Double = 2.4/3.2
You dont need it, just ude maxWidth for frame and fit aspect ratio without value

2024-05-30 10:04 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/CarouselOfGenres/ViewModel/GenresViewWithScrollViewModel.swift
> +        UserDefaults.standard.setValue(selectedGenres, forKey: "selectedGenres")
We don’t need to save in memory the genres, it’s not a cross launching value

2024-05-30 10:05 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/GenresScreen.swift
> +                                genres: viewModel.convertIdsInString(genres:viewModel.movie?.genres ?? [0])
Why are you using properties VM to pass to the VM method again? U can do it in VM side

2024-05-30 10:06 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/ViewModel/GenreScreenViewModel.swift
> +    func convertIdsInString(genres: [Int]) -> String {
Better do it on Request side where are you creating Request of Movies

2024-05-30 10:07 UTC, iosnickse requested changes
Small changes

2024-06-04 20:01 UTC, iosnickse requested changes

2024-06-04 20:01 UTC, iosnickse commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/ViewModel/GenreScreenViewModel.swift
> +    func fetchMoviesByGenre(completion: @escaping (Bool) -> Void) {
no need it

2024-06-04 20:01 UTC, iosnickse commented on swiftui_project/swiftui_project/Supports&Extensions/StringExtension/StringExtension.swift
> +        case "history":
Try to group by colour for few cases

2024-06-06 19:57 UTC, MaximBadanov commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/GenresScreen.swift
> +                Spacer(minLength: UISize.size8)
without it all ui  floats(

2024-06-06 19:58 UTC, MaximBadanov commented on swiftui_project/swiftui_project/ScreenWithGenres/GenresScreen/GenresScreen.swift
> +                    Spacer(minLength: UISize.size8)
same thing

2024-06-15 07:33 UTC, merged